### ISSUE TITLE
Random crash in Py_Finalize() in CommandLine mode

### ISSUE THREAD

**Issue by tmontaigu** [tmontaigu/CloudCompare-PythonPlugin#1]
In command line mode, a script such as :
```Python

import pycc
CC = pycc.GetCmdLineInstance()
assert CC is not None
cloudDescs = CC.clouds()
print(cloudDescs)
assert len(cloudDescs) == 1

cloud = cloudDescs[0]
print(cloud)
pc = cloud.pc #without this everything is fine
```

Will cause Py_Finalize() called in ~PythonPlugin() to crash (but not always)
adding a `del pc` or wrapping the code in a function: 
```Python

def main():
    # .... the code

if __name__ == '__main__'
    main()
```

seems to makes the problem disappear.

On the C++ side it  seems that calling the Py_Finalize() at the end of the command line processing function solves the problem

**Comment by WargodHernandez** [comment]
When I was experiencing similar issues on the ChaiScript plugin I modified main.cpp to include try/catch blocks around the stop plugins functions and called the same stop functions in the  ccCommandLineParser::cleanup() function prior to the removeClouds function.
In the plugin->stop() function I released everything I needed to



```C++
//release the plugins
	for ( ccPluginInterface *plugin : ccPluginManager::get().pluginList())
	{
		try
		{
			plugin->stop(); //just in case
		}
		catch (const std::exception & e)
		{
			QMessageBox::warning(0, QString("%1 - crashed!").arg(plugin->getName()), QString("%1 - crashed while attempting to stop\n%2").arg(plugin->getName()).arg(e.what()));
		}
		catch (...)
		{
			QMessageBox::warning(0, QString("%1 - crashed!").arg(plugin->getName()), QString("%1 - crashed while attempting to stop\n").arg(plugin->getName()));
		}
	}
```

**Comment by WargodHernandez** [comment]
Actually this brings up a good point I forgot about, everywhere CC touches a plugin for any reason we should be wrapping in try/catch blocks. I know I crashed the app a lot during testing until I did that. :)
@dgirardeau

**Comment by dgirardeau** [comment]
Well, that's always a good idea to do it anyway ;)

**Comment by tmontaigu** [comment]
I did not see that plugins had a `stop()` (and `start()`) methods however they do not seem to be called consistently

`stop` seems to only be called on plugins loaded in gui mode but not commandline mode
`start` doesn't seem to be called  at all (maybe only for plugins passed as command line argument in gui mode if the argument starts with `:start-plugin:`)


As for the bug it do not get it anymore since I moved the py::finamize()

**Comment by WargodHernandez** [comment]
I had moved the stop function out of the if/else block related to command line, so it always ran at the end.

https://github.com/CloudCompare/CloudCompare/blob/d49d0d8e329640beb646617ab9587f53fbec90b2/qCC/main.cpp#L275
