### ISSUE TITLE
[Question] Use x,y,z,label values of cloud after performing labelConnectedComponents

### ISSUE THREAD

**Issue by fredpeertje** [tmontaigu/CloudCompare-PythonPlugin#17]
Is it possible to read the x,y,z,label values of a cloud after performing `cccorelib.AutoSegmentationTools.labelConnectedComponents`? I can export it to a point cloud file and read it with a reader library... But, is it also possible to read it directly without saving + reading, like using it as a numpy array or something?

**Comment by tmontaigu** [comment]
You should be able to do it like this

```Python
# assuming pc is a ccPointCloud

# (Optional) Create (if it does not exists already) 
# a scalar field where we store the Labels
labelsSfIdx = pc.getScalarFieldIndexByName("Labels")
if labelsSfIdx == -1:
    labelsSfIdx = pc.addScalarField("Labels")
pc.setCurrentScalarField(labelsSfIdx)


numLabels = pycc.RunInThread(
    cccorelib.AutoSegmentationTools.labelConnectedComponents, pc, 11, False)
print("There are {} labels".format(numLabels))

# If we didn't create the Labels scalar field
# we would do here:
# labelsSfIdx = pc.getScalarFieldIndexByName("Default");

# Get the scalar field with labels and points coords as numpy array
labelsSf = pc.getScalarField(labelsSfIdx)
pointLabels = labelsSf.asArray()
pointsArray = pc.points()

# Just to show access to x, y, z
print(f"x: {pointsArray[:, 0]}")
print(f"y: {pointsArray[:, 1]}")
print(f"z: {pointsArray[:, 2]}")

allLabels = np.unique(pointLabels)

for label in allLabels:
    pointsOfLabel = pointsArray[pointLabels == label]
    print(f"Label {label}: {len(pointsOfLabel)} points")
```

**Comment by fredpeertje** [comment]
This looks good! :) 

However, I'm not able to install the standalone python wrapper in Windows and in Linux...
In Linux I get the following error:
`  ../../../src/PointProjectionTools.cpp:64:45: error: no matching function for call to ‘pybind11::class_<CCCoreLib::PointProjectionTools>::def_static(const char [20], <unresolved overloaded function type>, pybind11::arg, pybind11::arg, pybind11::arg_v)’`
when using:
`pip3 wheel --no-deps wrapper/cccorelib` 
I used the following two sudo apt-get installs: qt5-default and libqt5svg5-dev, and installed CloudCompare from source (if this was necessary?).


In Windows I get the following error:
` C:/Qt/5.15.2/msvc2019_64/include/QtCore/qsocketnotifier.h:113:33: error: enclosing class of constexpr non-static member function 'void* QSocketDescriptor::winHandle() const' is not a literal type`

Could you please tell me the exact versions that you use in linux? Ubuntu, Python, QT, gcc etc...

**Comment by tmontaigu** [comment]
Yes, some changes to CCCoreLib were done 3 days ago (https://github.com/CloudCompare/CCCoreLib/pull/63) and that broke the bindings.

I pushed on master a new commit that fixes that

**Comment by fredpeertje** [comment]
Ah thank you for pushing the fix to master. I'm able to install everything now. 

But... 😅 It seems that I can't use the getInstance() or RunInThread() functions (like in here: https://github.com/tmontaigu/CloudCompare-PythonPlugin/blob/master/script_examples/loading_a_file.py). 

`AttributeError: module 'pycc' has no attribute 'RunInThread'`

Look up all functions of pycc
```
import pycc
print("Look up all functions", dir(pycc))
```
Output:
`Look up all functions ['FileIOFilter', 'QFont', 'QMainWindow', 'QOpenGLWidget', 'QPointF', 'QProgressDialog', 'QSize', 'QWidget', 'Rgba', '_NormsIndexesArrayType', '_VectorCompressedNormType', '__ccGenericPointCloudTpl', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'cc2DLabel', 'ccBox', 'ccCone', 'ccCylinder', 'ccDish', 'ccDrawableObject', 'ccGLCameraParameters', 'ccGLMatrix', 'ccGLWindow', 'ccGenericGLDisplay', 'ccGenericMesh', 'ccGenericPointCloud', 'ccGenericPrimitive', 'ccGlobalShiftManager', 'ccHObject', 'ccInteractor', 'ccLog', 'ccMesh', 'ccObject', 'ccPlanarEntityInterface', 'ccPlane', 'ccPointCloud', 'ccProgressDialog', 'ccScalarField', 'ccShiftedObject', 'ccSphere', 'ccTorus']`

**Comment by tmontaigu** [comment]
Yes that is expected,

 it's not explained in the documentation yet, but every function listed in the [pycc runtime](https://tmontaigu.github.io/CloudCompare-PythonPlugin/pycc/runtime.html) page (and `RunInThread` is one of such function), is only available when the script is being run by the python embedded in the Plugin (so when you started CloudComapre with the Python plugin activated and you asked CC to run the script).

These functions are not available when running the script in a 'normal' python and that you installed the bindings as standalone packages. In that case you need to remove the RunInThread and directly call the function

**Comment by fredpeertje** [comment]
Oke, that explains it. What I want to do is load a *.laz file and call `labelConnectedComponents`. So, I think I have to use a library like laspy/pylas and convert that to a `ccPointCloud.

**Comment by tmontaigu** [comment]
Hum, There is currently no easy and efficient way to create a ccPointCloud from numpy arrays, that is still something I have to work on, I'll try to see this week/weekend what can be done about it.

The '"""easiest""" way to do stuff with the CloudCompare bindings is to compile CloudCompare yourself with the python plugin (and pdal plugin and use the [command line mode](https://tmontaigu.github.io/CloudCompare-PythonPlugin/getting_started.html#command-line), that way you can use cloudcompare to read the laz file directly in a ccPointCloud.

**Comment by tmontaigu** [comment]
I pushed some changes to make it easier to create ccPointClouds in python scripts.

There is an example [here](https://github.com/tmontaigu/CloudCompare-PythonPlugin/blob/master/script_examples/creating_point_cloud.py)

**Comment by fredpeertje** [comment]
Thank you, very useful!! 🙏 

I use the following code to ignore the components with less than a specified number of points. Similar to the option "Min. points per component" in CloudCompare.

```
minComponentSize = 1000
noiseLabel = 9999.0

pointLabelsNoise = np.copy(pointLabels)

# Slow... Set a noise label if component < minComponentSize
for label in allLabels:
    pointsOfLabel = pointsArray[pointLabels == label]
    if len(pointsOfLabel) < minComponentSize:
        pointLabelsNoise[pointLabelsNoise == label] = noiseLabel
        
# Save labelled point cloud 
las_labelled = pylas.create(point_format_id=3)
las_labelled.header = las.header
las_labelled.points = las.points
las_labelled.points['raw_classification'] = pointLabelsNoise
las_labelled.write(outfile)
```

You can close the GitHub issue 👍 👍

**Comment by tmontaigu** [comment]
Cool 😀,

Maybe you can do something like this to speed up the filtering

```Python
minComponentSize = 10_000
allLabels, counts = np.unique(pointLabels, return_counts=True) 
smallLabels = allLabels[counts < minComponentSize]
pointLabels[np.in1d(pointLabels, smallLabels)] = 0
```
