### ISSUE TITLE
Cannot install standalone cccorelib wrapper - Failed to checkout tag

### ISSUE THREAD

**Issue by fredpeertje** [tmontaigu/CloudCompare-PythonPlugin#20]
Hi tmontaigu,
I get a fatal error when trying to install the standalone cccorelib wrapper from the git master branch:

```
  fatal: reference is not a tree: be52fc2f9981a80cd457cd914f44f17f6ebf04f1
  CMake Error at cccorelib-subbuild/cccorelib-populate-prefix/tmp/cccorelib-populate-gitclone.cmake:40 (message):
    Failed to checkout tag: 'be52fc2f9981a80cd457cd914f44f17f6ebf04f1'

```

I managed to install pycc from the master on my Linux ubuntu-20.04.2.0 machine.

**Comment by tmontaigu** [comment]
It should be fixed on master, thanks for reporting

**Comment by fredpeertje** [comment]
Great, thank you!

**Comment by fredpeertje** [comment]
Oh, And I see pycc fails installing with the master. So, I clone the repo from an earlier commit that works: https://github.com/tmontaigu/CloudCompare-PythonPlugin/commit/5feb6fc2ccc4ee1124f16e3dd4353087322483d9

**Comment by tmontaigu** [comment]
Do you have any error message ? The ubuntu github actions works fine

**Comment by fredpeertje** [comment]
The error message was something with `missing wrappers.h`. But, deleting the `_skbuild` folder seems to fix it indeed haha
