### ISSUE TITLE
python plugin stuck at cmake

### ISSUE THREAD

**Issue by eiffelbastin** [tmontaigu/CloudCompare-PythonPlugin#25]
Hi sir,

I am quite new to coding. so this could be a stupid mistake from myside but pls do help me.

while trying to installing the python plugin I got stuck at the 5th step (Generate the cmake config) on the documentation.
I am using windows 10, CloudCompare v2.12 alpha 64 bit.

my cmake error's screenshot is here
![image](https://user-images.githubusercontent.com/83037376/131655732-fec5b6fa-d8c1-434c-b47b-e9d3fa149817.png)

my CMakeLists.txt is here
[CMakeLists.txt](https://github.com/tmontaigu/CloudCompare-PythonPlugin/files/7090332/CMakeLists.txt)

after the generation of pyccvenv  virtual environment, my python.exe is placed at C:\Windows\System32\pyccvenv\Scripts\python.exe

if these informations are sufficient please do help me.
and I would also like to know if it is possible to install the plugin with the .dll file that's been already generated by someone else, if yes please do share the python plugin's .dll file so that my installation will be at ease

**Comment by tmontaigu** [comment]
The "where the source is" should be the root of the CloudCompare dir

**Comment by eiffelbastin** [comment]
thank u so much sir !!!! I got the cmake generation successfully done..

at the same time, I am sorry to bother u again...

can u please explain the further steps to be followed. now I have a bunch of files generated from cmake like u can see in these pictures.
![image](https://user-images.githubusercontent.com/83037376/131699659-73d72147-aef2-40c5-8240-4abcadb4296e.png)
![image](https://user-images.githubusercontent.com/83037376/131699685-fb00ba5a-8a09-42dc-8cb6-da65407e0608.png)
![image](https://user-images.githubusercontent.com/83037376/131699738-e4d508a1-0ff4-4221-909f-860aaf90d421.png)

but none of them has a dll file that can be pasted into the plugins dir of cloudcompare.

**Comment by tmontaigu** [comment]
Open the PythonPlugin.sln in visual studio and run the 'INSTALL" target

**Comment by eiffelbastin** [comment]
sir, I have tried building like you said using visual studio, and the output is showing 'Build succeeded.' but I could not find any results or .dll file in any of the directories..... is there a way out?

![Screenshot (104)](https://user-images.githubusercontent.com/83037376/131720034-9b6ede2f-35de-45e7-98fa-a4aeff655026.png)
![Screenshot (102)](https://user-images.githubusercontent.com/83037376/131719743-eb78ec96-956f-4afe-b645-3abbec81f9fe.png)

**Comment by eiffelbastin** [comment]
sir while installing the plugin.sln I am getting this error (see screenshot) even after changing the debugging command target to the dir which consist the cloudcompare.exe as mentioned in this forum (http://www.danielgm.net/cc/forum/viewtopic.php?t=992)

![Screenshot (107)](https://user-images.githubusercontent.com/83037376/131825095-bab82f9d-4c38-41be-8a8c-9a7506d6dc8a.png)

please help me out of this

**Comment by tmontaigu** [comment]
You should first see how to compile CloudCompare from source without plugin by following the guide https://github.com/CloudCompare/CloudCompare/blob/master/BUILD.md. Then follow the instruction to compile with this plugin.

Or you can download the latest 2.12 alpha on CloudCompare's website and use this [installer](https://u.pcloud.link/publink/show?code=XZjJbdXZYEGTg7gcFAum74E8OPDlEBFQivUk)

**Comment by eiffelbastin** [comment]
got the plugin with the direct installer.
thank you very much, buddy !!!!! really appreciate it. u saved a lot of my time <3
