### ISSUE TITLE
Error in exportEntity

### ISSUE THREAD

**Issue by dinkan96** [tmontaigu/CloudCompare-PythonPlugin#27]
I used this code to import a bin file and it successfully did import the file

but 
I am getting some errors while extracting the files in the same bin file as individual CSV files

code:

import pycc
CC = pycc.GetInstance()
params = pycc.FileIOFilter.LoadParameters()
path = r"C:/Users/91828/Desktop/temp/test.bin"
obj = CC.loadFile(path, params)
obj = pycc.FileIOFilter.LoadFromFile(path, params)

output=CC.exportEntity(obj,'testname')

error :
![image](https://user-images.githubusercontent.com/90208474/132252156-769950e3-dbce-4e37-a75a-038060e18d03.png)

I tried to use this particular function
![image](https://user-images.githubusercontent.com/90208474/132252311-0a6c7600-b7b4-4d8f-9826-a9b7a36e90dc.png)

**Comment by tmontaigu** [comment]
The functiont "exportEntity" is only available on the "pycc.ccCommandLineInterface" which is what the `pycc.GetInstance()` returns in
command line mode. In regular/GUI mode `pycc.GetInstance()` returns a `pycc.ccPythonInstance`which does not have this function.

See https://tmontaigu.github.io/CloudCompare-PythonPlugin/python/pycc/runtime.html#pycc.GetInstance

I just added a `pycc.FileIOFilter.SaveToFile` function to be able to save files.

```Python
import pycc

params = pycc.FileIOFilter.LoadParameters()
path = r"C:/Users/91828/Desktop/temp/test.bin"
obj = pycc.FileIOFilter.LoadFromFile(path, params)

params = pycc.FileIOFilter.SaveParameters()
# Saving as bin
result = pycc.FileIOFilter.SaveToFile(obj, r'savedFromPlugin.bin', params)
# Saving as Laz (requires the Las plugin)
result = pycc.FileIOFilter.SaveToFile(obj.getChild(0), r'savedFromPlugin.laz', params)
```

This should work using the latest version from master or the latest installer.
