### ISSUE TITLE
How to draw a scanner location in using API

### ISSUE THREAD

**Issue by copyme** [tmontaigu/CloudCompare-PythonPlugin#37]
I would like to draw the scanner position from the code in using scanner pose and location loaded from an external TXT file.

Could you please let me know which part of the API allows for that? 

Some file formats have this scanner information already, e.g., e57, and CloudCompare can draw that. Here I would like to reproduce this, but in using external data.

![image](https://user-images.githubusercontent.com/456607/175321930-d285a06e-ab1a-44f0-929c-3ef711a51297.png)

**Comment by copyme** [comment]
I think I found the corresponding API. I did not test it yet but I think it is `pycc.ccSensor`.

**Comment by copyme** [comment]
Ok, in the end I just used spheres as `pycc.ccSensor` is implementing only the interface for specializations (that are not yet available).


In any case, thanks for the great work! Finally, CC is useful as it can be automated.

**Comment by tmontaigu** [comment]
> Ok, in the end I just used spheres as `pycc.ccSensor` is implementing only the interface for specializations (that are not yet available).
> 

I don't quite understand, what is `pycc.ccSensor` missing ?

I'll see what the e57 filter uses to set that information in the point cloud


> 
> 
> In any case, thanks for the great work! Finally, CC is useful as it can be automated.

Thanks

**Comment by tmontaigu** [comment]
I added some bindings to ccGBLSensor and ccCameraSensor, its seems that the E57 Filter uses them

**Comment by copyme** [comment]
@tmontaigu thanks! I think `ccSensor` in CC is just a base class, and it does not implement how the sensor should be drawn by CC.
