### ISSUE TITLE
beginner's problems

### ISSUE THREAD

**Issue by andrea-bistacchi** [tmontaigu/CloudCompare-PythonPlugin#38]
Hello, I just downloaded CC 2.12.2 and the [CloudCompare-PythonPlugin](https://github.com/tmontaigu/CloudCompare-PythonPlugin), and I am trying to perform some basic operation on a point cloud using the embedded Python Editor.

This works:
```
import numpy as np
import cccorelib as ccc
import pycc
# Pointer to CC instance
CC = pycc.GetInstance()
# Selected object
point_cloud = CC.getSelectedEntities()[0]
print("selected 5point_cloud: ", point_cloud)
print("point array: ", np.shape(point_cloud.points()))

```

But I would like to perform some calculation with x, y, z and scalars, and I always get errors, particularly with `addScalarField()`:
```
# Adding scalar field & doing something
idx = point_cloud.addScalarField("dist")
distance_array = point_cloud.getScalarField(idx).asArray()
distance_array[:] = np.zeros(np.shape(point_cloud.points()))
print(distance_array)

>>>RuntimeError: Failed to add scalar field

```
This is strange since I am doing as in the [examples](https://tmontaigu.github.io/CloudCompare-PythonPlugin/examples.html).

Thanks!

**Comment by tmontaigu** [comment]
Hello, generally when a scalar field could not be added its because, ascalar field with the same name exists.

So if for example you run your script twice, the first time, the scalar field is added, and the second time 
the scalar field cannot be added because is already exists

**Comment by andrea-bistacchi** [comment]
Thanks very much!
