### ISSUE TITLE
pycc installation

### ISSUE THREAD

**Issue by LoicBrouet** [tmontaigu/CloudCompare-PythonPlugin#40]
Hello, 

I'm trying to install the pycc plugin "As a CloudCompare Plugin" on Windows but I can't do it. The step 1 to 4 are ok (Clone this project into CloudCompare/plugins/private, Create a virtual environment via conda and activate it, and install dependencies. But after I'm not sure, I used the command "cmake ." to start the cmake generation for step 5, and for step 6/7 I built and installed cmake with cmake --build and cmake --install . but it doesn't work,  when I import pycc in python i have the error message 'No module named 'pycc' '. Could you please give more details about the step 6 and 7 (what has to be built and installed)?

Thank you for your help,
Loïc

**Comment by tmontaigu** [comment]
It is not very clear where you want to use pycc.

If you want to use it inside CloudCompre then follow `Building as Plugin`

If you want to use it outside of CloudCompare follow `Building as independent wheels`

**Comment by LoicBrouet** [comment]
Hello, thank you for your answer.

I want to use it in a python script, so as independent wheels.

My issue now is in the step "3. Run, Building the wheels", I have an error message "No CMAKE_C_COMPILER could be found." and "ERROR: Failed building wheel for cccorelib" (to sum up), and I have the same for pycc. 

I ran the command '$env:CMAKE_PREFIX_PATH+=";C:\Qt\5.15.2\msvc2019_64"' from the powershell of anaconda (in the folder of the project CloudCompare-PythonPlugin-master), and I didn't have any error message (the path to Qt is the right one). And then the commands: 
pip wheel --no-deps wrapper/cccorelib
pip wheel --no-deps wrapper/pycc '

I have the same issue with the direct installation:
pip install wrapper/cccorelib
pip install wrapper/pycc

Would you have any suggestion?¨

Thank you,
Loïc

**Comment by tmontaigu** [comment]
This error indicates that CMake could not find a compiler, this means you either do not have Visual Studio installed (Or Visual Studio Build Tools) to get the MSVC compiler. Or you have it installed, but its not detected properly.

- If you dont have visual studio installed, install it.
- If its installed (with the C++ 'workload') then you may need to run a script in the console you use to get your environment properly setup.

For the old cmd.exe:
```console
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
```

For PowerShell

```pwsh
Import-Module "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"

Enter-VsDevShell -DevCmdArguments '-arch=x64' -VsInstallPath 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community'
```
