### ISSUE TITLE
Docker instance of CC with python plugin installed

### ISSUE THREAD

**Issue by PascalVorwerkSaxion** [tmontaigu/CloudCompare-PythonPlugin#45]
Hi, i was wondering if there is some possibility of making a docker version of cloudcompare with this plugin installed? For a solution i am working on in my project we would like a version of cloud compare with this plugin installed, ideally through docker for ease of installation. 

Im wondering if any of you has done this before and can share any experience!

**Comment by tmontaigu** [comment]
basic docker files added in ba0be774c59ad76bb3da1f809cc4931dd9355455
