### ISSUE TITLE
Newly installed libraries (Requests etc) are not found in REPL/scripts etc.

### ISSUE THREAD

**Issue by PascalVorwerkSaxion** [tmontaigu/CloudCompare-PythonPlugin#46]
When installing new libraries through the GUI pip list, it correctly installs. But when i try to use these libraries in any script or the REPL it gives a not found module error.:
![image](https://user-images.githubusercontent.com/47634126/212316928-15ff9119-bbf6-4330-8bc0-9118be2a450f.png)

When finding the Python environment itself and entering the command mode i can however find the given modules.:

![image](https://user-images.githubusercontent.com/47634126/212316872-b085af1a-aa80-4429-b3a2-96f6a1b22393.png)

**Comment by PascalVorwerkSaxion** [comment]
REPL: 
![image](https://user-images.githubusercontent.com/47634126/212317013-627b4a23-f97d-48a4-8807-da79271a86ee.png)

**Comment by tmontaigu** [comment]
This looks very similat to https://github.com/tmontaigu/CloudCompare-PythonPlugin/issues/44

have you tried running cloudcompare as admin when installing puthon packages

**Comment by PascalVorwerkSaxion** [comment]
Ah very nice! It works now. I have ran as admin and checked the 'force' option aswell and its working. Thank you , i will close the issue!
