### ISSUE TITLE
Compute normals

### ISSUE THREAD

**Issue by DIMSpe** [tmontaigu/CloudCompare-PythonPlugin#47]
Hi,
is it possible to compute normals for a selected point cloud? As in the CloudCompare UI I would like to set the following parameter: "local surface model", "Octree-radius" and "Orientation". 

import pycc
import cccorelib

cc = pycc.GetInstance()
pointCloud = cc.getSelectedEntities()[0]
pointCloudNy = pointCloud.clone()
pointCloudNy.setName(pointCloud.getName()+ "_Ny")
print(pointCloudNy)

# compute normals ...???

cc.addToDB(pointCloudNy)
cc.setSelectedInDB(pointCloudNy)
cc.updateUI()

I'm just starting with pycc and hope the question isn't too stupid.

**Comment by tmontaigu** [comment]
I'm not sure that all the necessary functions are bound in pycc to enable that, I will check

**Comment by DIMSpe** [comment]
Hi,
thanks you for your effort ;-)

**Comment by tmontaigu** [comment]
There is an example here https://github.com/tmontaigu/CloudCompare-PythonPlugin/pull/48/files#diff-df5d1e1f9cea11152e63ac841fc7634e5c7afdb25b75447aad96ade140e12e9d

But it cannot be used right now, the changes have not been merged

**Comment by tmontaigu** [comment]
No computing normals is not yet possible, there is some not so trivial issue to fix to be able to have this feature in python
