### ISSUE TITLE
Use "crop2d" command in commandline

### ISSUE THREAD

**Issue by squowse** [tmontaigu/CloudCompare-PythonPlugin#49]
Hi, please forgive my lack of familiarity with cloudcompare and this plugin.

I wish to use the crop2d command (this is a command line command i believe). 

I want to operate it as a script, loading in a list of co-ordinates from a file. I'm familiar with Python so have ended up here.

I would really like to continue using the GUI to see the effects of changes etc - Is this possible? 
Can the python script issue a command line command that affects the current database viewed on screen? 

I've started using the python editor in your plugin. That's from the cloudcompare GUI.

**Comment by tmontaigu** [comment]
This in theory possible, but not exactly as you described,

You won't be able to call the same cloudcompare  command for crop2d that you would use on the command line.

You would have to use the python bindings that this plugin provide to make a python function that has similar behaviour.

Mainly you would need to call the `ccPointCloud::crop2d` function, however it is not available in the bindings yet so you have to wait for that to be added here first

**Comment by squowse** [comment]
> This in theory possible, but not exactly as you described,
> 
> You won't be able to call the same cloudcompare command for crop2d that you would use on the command line.
> 
> You would have to use the python bindings that this plugin provide to make a python function that has similar behaviour.
> 
> Mainly you would need to call the `ccPointCloud::crop2d` function, however it is not available in the bindings yet so you have to wait for that to be added here first

Thanks that sounds great. I'll wait 👍
