### ISSUE TITLE
Change the color scale by script

### ISSUE THREAD

**Issue by DIMSpe** [tmontaigu/CloudCompare-PythonPlugin#51]
Hallo,

I designed an own color scale. Within the gui I can choose the color scale. My test script:

ColorScale=pycc.ccColorScale("01_Test", "{5df8e582-31a1-4aeb-8015-4374326b5c54}")
TestColorScale = pycc.ccColorScalesManager.GetScale("{5df8e582-31a1-4aeb-8015-4374326b5c54}")
pointCloudScalarField.setColorScale(TestColorScale)

and get an AttributeError.

Any idea

Maik

**Comment by tmontaigu** [comment]
You have to do


```Python
import pycc

colorScaleManager = pycc.ccColorScalesManager().GetUniqueInstance()

colorScaleManager.getScale("{5df8e582-31a1-4aeb-8015-4374326b5c54}")
```
