### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by Luisjupm** [tmontaigu/CloudCompare-PythonPlugin#59]
Dear all, 
i am a totally beginner in programming.... so maybe the question is quite obvious. 

I want to create a python plugin that appears as an independent button on the bar, such as the CANUPO plugin for example. 

There is any possibility? how is the process?

Many thanks, 
Luis

**Comment by tmontaigu** [comment]
Its is not exactly possible but something similar exists.

You can either use the 'script regiser' menu then add a script by browsing for it, then it will appear in the same 'script register' menu for easy access.

Or you can look at https://github.com/tmontaigu/CloudCompare-PythonPlugin/tree/master/script_examples/plugin_examples
create you plugin based on that.

Then in cloud compare open the python plugin settings, click the dialog to edit plugins paths to be able to add the folder where you stored your plugin.

Then restart cloudcompare click on the action launcher (skyrocket icon) and you will see the actions you defined

**Comment by Luisjupm** [comment]
Many thanks for the response. I going to close this post

And congratulations for the effort done¡¡ it is a very useful application
