### ISSUE TITLE
I'm beginner

### ISSUE THREAD

**Issue by matha0** [tmontaigu/CloudCompare-PythonPlugin#73]
Sorry, I'm a beginner and don't know anything.
Could you please explain to me in simple terms how to build cmake for plugin?
If it isn't too much trouble, I would like to have a clear explanation of how to do it afterwards.

**Comment by tmontaigu** [comment]
Are you on windows ? If yes then just use the installer.

If you are a true true beginner (never compiled a program before) I'm afraid I won't be able to help you

**Comment by matha0** [comment]
OK. I'll try it. thank you.
