### ISSUE TITLE
Unable to convert when using getTypeName - QString

### ISSUE THREAD

**Issue by jonathwolf** [tmontaigu/CloudCompare-PythonPlugin#74]
Hi,
I want to use the planes from CloudCompare in my script. For this I need to access the name of the plane. However, I have the problem that since PyQt5 the type QString is no longer available and so I cannot access the name of the plane. Are there any ideas how to fix it?

My script:
>import pycc
>CC = pycc.GetInstance()
>planes = CC.getSelectedEntities()
>for i in range(len(planes)):
>    print(pycc.ccGenericPrimitive.getTypeName(planes[i]))

TypeError: Unable to convert function return value to a Python type! The signature was
	(self: pycc.ccGenericPrimitive) -> QString

**Comment by tmontaigu** [comment]
I don't know if that's because you tried different things because it was not working
but you should be doing `planes[i].getTypeName()`

There was indeed a problem its going to be fixed by https://github.com/tmontaigu/CloudCompare-PythonPlugin/pull/75

**Comment by tmontaigu** [comment]
However, getTypeName will always return "Plane" for planes, if you want to get the name that appears in the GUI its `planes[i].getName()` which already works

**Comment by jonathwolf** [comment]
That works, thanks a lot for the answer.
