### ISSUE TITLE
Using the pip package manager with 2.13.beta

### ISSUE THREAD

**Issue by lmweidner** [tmontaigu/CloudCompare-PythonPlugin#80]
Hi, this is my first time trying to use the pycc library in CloudCompare. Currently I'm just naively installing the plugin with the latest version of CloudCompare where it's an easy option (super excited to see that btw).
 
Currently I'm not able to use the pip package manager tool to install other packages. I've tried installing scikit-spatial, trimesh, and pyperclip. They appear to successfully install and show up in the package list, but show up as "module not found" when importing them in a script. I'm wondering if there's some PATH modifications that I need to make on the backend, or alternatively maybe this is a feature in-progress and not yet functional ;)

Thanks for the work on this project and I'm excited to test it out more.

**Comment by tmontaigu** [comment]
What are you doing exactly ? Are you using the command line or the window/interface provided by the plugin ?

You have to run cloudcompare as administrator for the installation of packages to truly work 

https://github.com/tmontaigu/CloudCompare-PythonPlugin/issues/44
